spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bd2?serverTimezone=America/Buenos_Aires&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
    username: root
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

    database: mysql
    open-in-view: true
